### PR TITLE
Avoid silently skipping gcc-specific code

### PR DESCRIPTION
**Pull request by TheCodeArtist**
As discussed created this PR to review the possibility to support gcc-specific code in the input `.h` header files.

### CODE REVIEW

**Comment by Alan-R** [comment]
How about if you add a command line option to enable this behavior?

That would lower the risk to near-zero...

**Comment by TheCodeArtist** [comment]
You are right.  
A separate command-line option that triggers this new behavior  
would eliminate the chances of any unexpected regressions.

Let me gives this some more thought and publish an updated pull-request.
Thanks

**Comment by Alan-R** [comment]
OK. Let me know when you're ready with the new change.

**Comment by TheCodeArtist** [comment]
Pushed the new change for review as a new PR - https://github.com/ctypesgen/ctypesgen/pull/104

**Pull request closed without merging**
